---
    name: Package Docker
    
    env:
      DOCKERHUB_REPOSITORY: 3uclid3/nos-buildenv
      LLVM_VERSION: 18
    
    on:
      push:
        branches:
          - 'main'
      schedule:
        # At 03:00 on Sunday to update the image
        - cron: '0 3 * * 0'
    
    jobs:
      package-docker:
        name: Package Docker
        runs-on: ubuntu-22.04
    
        steps:
          - name: Checkout
            uses: actions/checkout@v3
    
          - name: Setup Docker Buildx
            uses: docker/setup-buildx-action@v2
          
          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          - name: Build Image
            uses: docker/build-push-action@v4
            with:
              context: "{{defaultContext}}:docker/llvm"
              load: true
              build-args: "LLVM_VERSION=${{env.LLVM_VERSION}}"
              tags: "${{ env.DOCKERHUB_REPOSITORY }}:test"
              
          - name: Test Image
            run: |
              docker run --rm ${{ env.DOCKERHUB_REPOSITORY }}:test
    
          - name: Push Image
            uses: docker/build-push-action@v4
            with:
              context: "{{defaultContext}}:docker"
              push: true
              tags: "${{ env.DOCKERHUB_REPOSITORY }}:latest, ${{ env.DOCKERHUB_REPOSITORY }}:llvm-${{env.LLVM_VERSION}}, ${{ env.DOCKERHUB_REPOSITORY }}:l-${{env.LLVM_VERSION}}"
              labels: "nos.buildenv.llvm=${{env.LLVM_VERSION}},  nos.buildenv.github.sha=${{ github.sha }}"
